import type { Metadata } from "next";
import { DM_Sans as FontSans } from "next/font/google"
import { Poppins } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import DefaultWrapper from "@/components/default-wrapper";
import Header from "@/components/header";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: "--font-poppins",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable,
					poppins.variable
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<DefaultWrapper>
						<Header/>
						{children}
					</DefaultWrapper>
				</ThemeProvider>
			</body>
		</html>
	);
}
